require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('./models/Product');
const User = require('./models/User');

// ─── Curated products: every image matches the product name exactly ────────
const products = [
    // ── MEN'S CLOTHING ────────────────────────────────────────────────────
    {
        name: 'Classic White T-Shirt',
        description: 'Crisp 100% cotton tee with a relaxed fit. A true wardrobe essential for everyday wear.',
        price: 29.99, category: 'Clothing', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Oxford Button-Down Shirt',
        description: 'Classic Oxford shirt perfect for smart-casual occasions. Wrinkle-resistant cotton blend.',
        price: 59.99, category: 'Clothing', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Blue', hex: '#4A90D9' }, { name: 'White', hex: '#FFFFFF' }],
        images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Slim Fit Chinos',
        description: 'Modern slim-fit chinos in a versatile neutral tone. Goes from office to weekend seamlessly.',
        price: 69.99, category: 'Clothing', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Beige', hex: '#D4C5A9' }, { name: 'Brown', hex: '#8B5E3C' }],
        images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Denim Jacket',
        description: 'Timeless denim jacket with a tailored fit and contrast stitching. Pairs with everything.',
        price: 89.99, category: 'Clothing', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Blue', hex: '#5B7FA6' }],
        images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Wool Overcoat',
        description: 'Premium wool-blend overcoat for cold weather elegance. Sharp silhouette, lasting warmth.',
        price: 199.99, category: 'Clothing', department: 'Men',
        sizes: ['M', 'L', 'XL'],
        colors: [{ name: 'Gray', hex: '#808080' }, { name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    // ── MEN'S SHOES ───────────────────────────────────────────────────────
    {
        name: 'White Leather Sneakers',
        description: 'Clean, minimalist white leather sneakers. Versatile enough for any casual outfit.',
        price: 79.99, category: 'Shoes', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'White', hex: '#FFFFFF' }],
        images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Classic Running Shoes',
        description: 'Lightweight, breathable running shoes with superior cushioning for all-day comfort.',
        price: 109.99, category: 'Shoes', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Black', hex: '#000000' }, { name: 'Blue', hex: '#0057B7' }],
        images: ['https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Brown Derby Shoes',
        description: 'Handcrafted full-grain leather derby shoes. Timeless, refined and built to last.',
        price: 149.99, category: 'Shoes', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Brown', hex: '#8B4513' }],
        images: ['https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Black Chelsea Boots',
        description: 'Sleek Chelsea boots in polished black leather. Easy pull-on style with elastic side panels.',
        price: 129.99, category: 'Shoes', department: 'Men',
        sizes: ['M', 'L', 'XL'],
        colors: [{ name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Suede Desert Boots',
        description: 'Classic suede desert boots with a crepe sole. Casual elegance for every season.',
        price: 99.99, category: 'Shoes', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Brown', hex: '#8B5E3C' }, { name: 'Gray', hex: '#808080' }],
        images: ['https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    // ── WOMEN'S CLOTHING ──────────────────────────────────────────────────
    {
        name: 'Floral Wrap Dress',
        description: 'Feminine wrap dress in vibrant floral print with a flattering V-neckline.',
        price: 79.99, category: 'Clothing', department: 'Women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Red', hex: '#C0392B' }, { name: 'Blue', hex: '#2980B9' }],
        images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Classic Black Blazer',
        description: 'Structured black blazer for power dressing. Tailored fit that flatters every figure.',
        price: 119.99, category: 'Clothing', department: 'Women',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1548549557-dbe9946621da?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'High-Waist Tailored Pants',
        description: 'Elegant high-waist trousers with a wide-leg silhouette. Effortlessly polished.',
        price: 89.99, category: 'Clothing', department: 'Women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Black', hex: '#000000' }, { name: 'White', hex: '#FFFFFF' }],
        images: ['https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Cashmere Knit Sweater',
        description: 'Luxuriously soft cashmere-blend knit sweater. Ribbed cuffs and hem for a refined finish.',
        price: 149.99, category: 'Clothing', department: 'Women',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Beige', hex: '#D4C5A9' }, { name: 'Pink', hex: '#E8A0BF' }],
        images: ['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Pleated Midi Skirt',
        description: 'Elegant pleated midi skirt in flowing fabric. Moves beautifully and styles with ease.',
        price: 69.99, category: 'Clothing', department: 'Women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Green', hex: '#2D6A4F' }, { name: 'Blue', hex: '#2980B9' }],
        images: ['https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    // ── WOMEN'S SHOES ─────────────────────────────────────────────────────
    {
        name: 'Strappy Heeled Sandals',
        description: 'Elegant strappy heeled sandals with adjustable ankle strap. Ideal for evenings out.',
        price: 89.99, category: 'Shoes', department: 'Women',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Black', hex: '#000000' }, { name: 'Beige', hex: '#D4C5A9' }],
        images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Leather Ankle Boots',
        description: 'Chunky-sole leather ankle boots. Bold, versatile, and made to turn heads.',
        price: 119.99, category: 'Shoes', department: 'Women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Brown', hex: '#8B4513' }, { name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'White Platform Sneakers',
        description: 'Chunky platform sneakers that add height with maximum comfort. A street-style staple.',
        price: 99.99, category: 'Shoes', department: 'Women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'White', hex: '#FFFFFF' }],
        images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Block Heel Mules',
        description: 'Comfortable block heel mules with an open toe. Chic, practical and easy to wear.',
        price: 79.99, category: 'Shoes', department: 'Women',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Beige', hex: '#D4C5A9' }, { name: 'Red', hex: '#C0392B' }],
        images: ['https://images.unsplash.com/photo-1596703263926-422ed835f3c2?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Slip-On Leather Loafers',
        description: 'Classic leather loafers that go with anything. Effortlessly chic from day to night.',
        price: 109.99, category: 'Shoes', department: 'Women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Black', hex: '#000000' }, { name: 'Brown', hex: '#8B4513' }],
        images: ['https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    // ── KIDS' CLOTHING ────────────────────────────────────────────────────
    {
        name: 'Superhero Graphic Tee',
        description: 'Colorful superhero print tee that kids absolutely love. 100% soft breathable cotton.',
        price: 19.99, category: 'Clothing', department: 'Kids',
        sizes: ['S', 'M'],
        colors: [{ name: 'Blue', hex: '#2980B9' }, { name: 'Red', hex: '#C0392B' }],
        images: ['https://images.unsplash.com/photo-1519238263430-660d12402f09?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Denim Dungarees',
        description: 'Classic denim dungarees with adjustable straps. Easy to wear and play in all day.',
        price: 34.99, category: 'Clothing', department: 'Kids',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Blue', hex: '#5B7FA6' }],
        images: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Rainbow Zip Hoodie',
        description: 'Fun rainbow-print zip hoodie. Warm, cozy, machine washable, and kid-approved.',
        price: 39.99, category: 'Clothing', department: 'Kids',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Pink', hex: '#E8A0BF' }, { name: 'Blue', hex: '#2980B9' }],
        images: ['https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Floral Summer Dress',
        description: 'Sweet floral dress with smocked bodice. Perfect for sunny days and special occasions.',
        price: 29.99, category: 'Clothing', department: 'Kids',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Pink', hex: '#E8A0BF' }],
        images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Cozy Fleece Joggers',
        description: 'Super-soft fleece joggers with elastic waistband and cuffs. Built for playtime.',
        price: 24.99, category: 'Clothing', department: 'Kids',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Gray', hex: '#808080' }, { name: 'Blue', hex: '#2980B9' }],
        images: ['https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    // ── KIDS' SHOES ───────────────────────────────────────────────────────
    {
        name: 'Light-Up Sneakers',
        description: 'Fun light-up sneakers kids adore. Comfortable fit with easy velcro strap closure.',
        price: 34.99, category: 'Shoes', department: 'Kids',
        sizes: ['S', 'M'],
        colors: [{ name: 'Pink', hex: '#E8A0BF' }, { name: 'Blue', hex: '#2980B9' }],
        images: ['https://images.unsplash.com/photo-1515347619252-60a6bf4fffce?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Canvas Slip-On Shoes',
        description: 'Easy slip-on canvas shoes in fun colors. Lightweight and great for school.',
        price: 24.99, category: 'Shoes', department: 'Kids',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Red', hex: '#C0392B' }, { name: 'Blue', hex: '#2980B9' }],
        images: ['https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Waterproof Rain Boots',
        description: 'Colorful rubber rain boots with non-slip sole. Keep little feet dry and happy.',
        price: 29.99, category: 'Shoes', department: 'Kids',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Yellow', hex: '#F1C40F' }, { name: 'Green', hex: '#2ECC71' }],
        images: ['https://images.unsplash.com/photo-1583338917451-face2751d8d5?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Sports Training Shoes',
        description: 'Durable, lightweight training shoes with extra cushioning for active kids on the move.',
        price: 44.99, category: 'Shoes', department: 'Kids',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Green', hex: '#2ECC71' }, { name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Mary Jane Flats',
        description: 'Classic Mary Jane flats in shiny patent leather. Adorable, comfortable and easy to wear.',
        price: 32.99, category: 'Shoes', department: 'Kids',
        sizes: ['S', 'M'],
        colors: [{ name: 'Black', hex: '#000000' }, { name: 'Pink', hex: '#E8A0BF' }],
        images: ['https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },

    // ── MEN'S CLOTHING (extra) ────────────────────────────────────────────
    {
        name: 'Classic Polo Shirt',
        description: 'Breathable piqué cotton polo. A preppy staple that works from golf course to brunch.',
        price: 49.99, category: 'Clothing', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Navy', hex: '#1B2A4A' }, { name: 'White', hex: '#FFFFFF' }],
        images: ['https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Pullover Hoodie',
        description: 'Heavyweight fleece pullover hoodie with kangaroo pocket. Comfort for any occasion.',
        price: 64.99, category: 'Clothing', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Gray', hex: '#808080' }, { name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1556821840-3a63f15732ce?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Tapered Joggers',
        description: 'Slim tapered joggers in French terry fabric. Athletic comfort meets modern style.',
        price: 54.99, category: 'Clothing', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Black', hex: '#000000' }, { name: 'Navy', hex: '#1B2A4A' }],
        images: ['https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Linen Summer Shirt',
        description: 'Lightweight linen shirt perfect for warm weather. Relaxed fit, natural breathability.',
        price: 69.99, category: 'Clothing', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Beige', hex: '#D4C5A9' }],
        images: ['https://images.unsplash.com/photo-1589310243389-96a5483213a8?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Bomber Jacket',
        description: 'Classic MA-1 bomber jacket in nylon. Timeless silhouette with ribbed collar and cuffs.',
        price: 119.99, category: 'Clothing', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Black', hex: '#000000' }, { name: 'Olive', hex: '#556B2F' }],
        images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Ribbed Turtleneck Sweater',
        description: 'Fine-knit ribbed turtleneck for a sleek, refined look. Essential for layering.',
        price: 79.99, category: 'Clothing', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Black', hex: '#000000' }, { name: 'Cream', hex: '#FFFDD0' }],
        images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Cargo Pants',
        description: 'Utility cargo pants with multiple pockets. Rugged style meets everyday functionality.',
        price: 74.99, category: 'Clothing', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Olive', hex: '#556B2F' }, { name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Swim Shorts',
        description: 'Quick-dry swim shorts with mesh lining. Bold print, elastic waist, ready for the beach.',
        price: 39.99, category: 'Clothing', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Blue', hex: '#2980B9' }, { name: 'Green', hex: '#27AE60' }],
        images: ['https://images.unsplash.com/photo-1565693413579-8a73ffa8bdf5?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },

    // ── MEN'S SHOES (extra) ───────────────────────────────────────────────
    {
        name: 'Leather Penny Loafers',
        description: 'Polished penny loafers in smooth leather. The epitome of smart-casual footwear.',
        price: 134.99, category: 'Shoes', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Brown', hex: '#8B4513' }, { name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1531310197839-ccf54634509e?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'High-Top Canvas Sneakers',
        description: 'Iconic high-top canvas sneakers. Timeless street style in a durable vulcanized sole.',
        price: 59.99, category: 'Shoes', department: 'Men',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1463100099107-aa0980c362e6?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Waterproof Hiking Boots',
        description: 'Gore-Tex waterproof hiking boots with ankle support. Built for the trail, comfortable in the city.',
        price: 169.99, category: 'Shoes', department: 'Men',
        sizes: ['M', 'L', 'XL'],
        colors: [{ name: 'Brown', hex: '#8B5E3C' }, { name: 'Gray', hex: '#808080' }],
        images: ['https://images.unsplash.com/photo-1520219306100-ec4afeeefe58?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },

    // ── WOMEN'S CLOTHING (extra) ──────────────────────────────────────────
    {
        name: 'Wide-Leg Linen Trousers',
        description: 'Breezy wide-leg linen trousers in an elegant drape. Perfect for warm weather dressing.',
        price: 84.99, category: 'Clothing', department: 'Women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Beige', hex: '#D4C5A9' }],
        images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Classic Trench Coat',
        description: 'Iconic double-breasted trench coat in water-resistant cotton gabardine. A perennial classic.',
        price: 229.99, category: 'Clothing', department: 'Women',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Beige', hex: '#D4C5A9' }, { name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1520367445093-50dc08a59d9d?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Ribbed Crop Top',
        description: 'Stretchy ribbed crop top that pairs with everything. Simple, fitted, endlessly versatile.',
        price: 29.99, category: 'Clothing', department: 'Women',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'White', hex: '#FFFFFF' }, { name: 'Black', hex: '#000000' }, { name: 'Pink', hex: '#E8A0BF' }],
        images: ['https://images.unsplash.com/photo-1554568218-0f1715e72254?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Boho Maxi Dress',
        description: 'Flowing boho maxi dress with tiered skirt and adjustable straps. Festival-ready.',
        price: 94.99, category: 'Clothing', department: 'Women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Rust', hex: '#B7410E' }, { name: 'Blue', hex: '#2980B9' }],
        images: ['https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Oversized Cardigan',
        description: 'Chunky knit oversized cardigan with deep pockets. Wrap yourself in cozy luxury.',
        price: 109.99, category: 'Clothing', department: 'Women',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Camel', hex: '#C19A6B' }, { name: 'Gray', hex: '#808080' }],
        images: ['https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Faux Leather Biker Jacket',
        description: 'Edgy faux leather biker jacket with asymmetric zip. Add instant attitude to any outfit.',
        price: 139.99, category: 'Clothing', department: 'Women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Black', hex: '#000000' }, { name: 'Brown', hex: '#8B4513' }],
        images: ['https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Slim Fit Jumpsuit',
        description: 'Tailored slim-fit jumpsuit in stretch crepe. One-piece elegance for effortless dressing.',
        price: 114.99, category: 'Clothing', department: 'Women',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Black', hex: '#000000' }, { name: 'Navy', hex: '#1B2A4A' }],
        images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'High-Rise Skinny Jeans',
        description: 'Classic high-rise skinny jeans in stretch denim. Flattering fit from waist to ankle.',
        price: 79.99, category: 'Clothing', department: 'Women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Blue', hex: '#5B7FA6' }, { name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },

    // ── WOMEN'S SHOES (extra) ─────────────────────────────────────────────
    {
        name: 'Ballet Flats',
        description: 'Timeless leather ballet flats with cushioned insole. Lightweight, elegant, all-day comfort.',
        price: 74.99, category: 'Shoes', department: 'Women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Black', hex: '#000000' }, { name: 'Beige', hex: '#D4C5A9' }],
        images: ['https://images.unsplash.com/photo-1518049362265-d5b2a6467637?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Knee-High Leather Boots',
        description: 'Sleek knee-high boots in genuine leather with a modest heel. Drama with every step.',
        price: 189.99, category: 'Shoes', department: 'Women',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Black', hex: '#000000' }, { name: 'Brown', hex: '#8B4513' }],
        images: ['https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Espadrille Wedges',
        description: 'Classic jute espadrille wedges with ankle tie. Vacation-ready summer style.',
        price: 64.99, category: 'Shoes', department: 'Women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Beige', hex: '#D4C5A9' }, { name: 'White', hex: '#FFFFFF' }],
        images: ['https://images.unsplash.com/photo-1562273138-f46be4ebdf33?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Pointed Toe Heels',
        description: 'Elegant pointed-toe stiletto heels in suede. The perfect finishing touch for any formal look.',
        price: 124.99, category: 'Shoes', department: 'Women',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Black', hex: '#000000' }, { name: 'Red', hex: '#C0392B' }],
        images: ['https://images.unsplash.com/photo-1596703263926-422ed835f3c2?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Oxford Brogues',
        description: 'Wingtip brogue oxford shoes in full-grain leather. Androgynous elegance, effortlessly chic.',
        price: 114.99, category: 'Shoes', department: 'Women',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [{ name: 'Brown', hex: '#8B4513' }, { name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },

    // ── KIDS (extra) ──────────────────────────────────────────────────────
    {
        name: 'Puffer Jacket',
        description: 'Warm puffer jacket with water-resistant shell. Kids stay cozy and dry all winter long.',
        price: 54.99, category: 'Clothing', department: 'Kids',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Red', hex: '#C0392B' }, { name: 'Navy', hex: '#1B2A4A' }],
        images: ['https://images.unsplash.com/photo-1604671801908-6f0c6a092c05?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Kids Swim Shorts',
        description: 'Quick-dry printed swim shorts with elastic waist. Fun patterns for summer pool days.',
        price: 22.99, category: 'Clothing', department: 'Kids',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Blue', hex: '#2980B9' }, { name: 'Green', hex: '#27AE60' }],
        images: ['https://images.unsplash.com/photo-1519238263430-660d12402f09?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'School Uniform Set',
        description: 'Smart school uniform set — polo shirt and trousers. Durable, easy-care, always presentable.',
        price: 44.99, category: 'Clothing', department: 'Kids',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Navy', hex: '#1B2A4A' }, { name: 'Gray', hex: '#808080' }],
        images: ['https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Dinosaur Print Pyjamas',
        description: 'Super soft cotton pyjamas with all-over dinosaur print. Bedtime just got more exciting.',
        price: 27.99, category: 'Clothing', department: 'Kids',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Green', hex: '#27AE60' }, { name: 'Blue', hex: '#2980B9' }],
        images: ['https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
    {
        name: 'Kids Ankle Boots',
        description: 'Sturdy ankle boots with easy side zip. Stylish, practical and built for little adventurers.',
        price: 42.99, category: 'Shoes', department: 'Kids',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Brown', hex: '#8B4513' }, { name: 'Black', hex: '#000000' }],
        images: ['https://images.unsplash.com/photo-1515347619252-60a6bf4fffce?auto=format&fit=crop&w=800&q=80'],
        isTrending: false, inStock: true,
    },
    {
        name: 'Glitter Ballet Flats',
        description: 'Sparkly glitter ballet flats every little one will love. Comfortable enough for all-day wear.',
        price: 28.99, category: 'Shoes', department: 'Kids',
        sizes: ['S', 'M'],
        colors: [{ name: 'Pink', hex: '#E8A0BF' }, { name: 'Silver', hex: '#C0C0C0' }],
        images: ['https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=800&q=80'],
        isTrending: true, inStock: true,
    },
];

const seedData = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/fashion-ecommerce', {
            dbName: 'fashion-ecommerce',
        });
        console.log('✓ MongoDB Connected: fashion-ecommerce database');

        await Product.deleteMany({});
        await User.deleteMany({});
        console.log('✓ Existing data cleared');

        // Pass plain text — the User model's pre('save') hook handles hashing
        await User.create([
            {
                name: 'Admin User',
                email: 'admin@example.com',
                password: 'admin123',
                role: 'admin',
                isAdmin: true,
            },
            {
                name: 'Jane Doe',
                email: 'jane@example.com',
                password: 'password123',
                role: 'user',
                isAdmin: false,
            },
        ]);
        console.log('✓ Users seeded  (admin@example.com / admin123)');

        await Product.insertMany(products);
        console.log(`✓ ${products.length} products seeded — every image matches its product name`);

        process.exit(0);
    } catch (error) {
        console.error('✗ Seeder error:', error);
        process.exit(1);
    }
};

seedData();
